import operator
from typing import TypedDict, List, Annotated

class AgentState(TypedDict):
    # Metadata
    task_id: str                # Unique identifier for this agent run (e.g., GitHub issue #)
    instructions: str           # The raw request from the user/issue body
    repo_url: str               # The target repository SSH URL to clone
    repo_full_name: str         # The target repository full name (e.g., User/repo)
    installation_id: str        # GitHub App Installation ID for API interaction
    
    # Execution Tracking
    workspace_path: str         # The local path where the isolated repo was cloned
    current_branch: str         # The random branch name generated for this task
    
    # LangGraph Memory
    history: Annotated[List[str], operator.add] # Log of all steps taken (for Slack status)
    compiler_errors: List[str]  # Accumulated xcodebuild errors
    retries_count: int          # Hard limit to prevent infinite loops (max 3)
    blueprint: dict             # The JSON FeatureBlueprint generated by the Planner Node
    mcp_context: str            # External knowledge pulled from Context Aggregator
    agent_skills: str           # Parsed .lios-config.yml and .agent/skills/*.md files
    active_subagents: List[str] # Which sub-agents the Router has dispatched (e.g. ["ui", "network"])
    opencode_session_id: str    # Unique session token to cleanly resume PR review comments
    screenshot_path: str        # Local workspace path to the generated UI pixel verification screenshot
    video_path: str             # Local workspace path to the .mp4 runtime video telemetry
    device_udid: str            # The active iOS Simulator UDID used for Maestro navigation
    bundle_id: str              # The app's CFBundleIdentifier for Maestro interactions
